#!/usr/bin/env ruby

require_relative './lib/sudoku_parser'
require_relative './lib/region'
require_relative './lib/combiner'
require_relative './lib/sudoku_validator'

file    = File.open(ARGV[0])
regions = SudokuParser.new(file).parse
file.close

combined_regions =
  Combiner.new(collection: regions, queries: ['valid?', 'complete?'])

result = SudokuValidator.new(combined_regions).validate
puts result
